In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
bd_file = "binge_drinking.csv"
bd_df = pd.read_csv(bd_file)
bd_df.head()

,ID,Year,LocationAbbr,LocationDesc,Class,Topic,Indicator,Response,DataSource,Data_Value_Unit,...,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder,FootnoteType,FootNoteSymbol,FootnoteText,URL,DatasourceAbbr,Agency
0,2924470.0,2016.0,US,"All States, DC and Territories (median) **",Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,Yes,BRFSS,%,...,Overall,_RFBING5,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2924471.0,2016.0,US,"All States, DC and Territories (median) **",Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,No,BRFSS,%,...,Overall,_RFBING5,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2925366.0,2016.0,UW,All States and DC (median) **,Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,Yes,BRFSS,%,...,Overall,_RFBING5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2925367.0,2016.0,UW,All States and DC (median) **,Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,No,BRFSS,%,...,Overall,_RFBING5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2695131.0,2016.0,AL,Alabama,Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,Yes,BRFSS,%,...,Overall,_RFBING5,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
bd_df = bd_df[['Year', 'LocationAbbr', 'LocationDesc', 'Topic', 'Response', 'Data_Value_Unit', 'Data_Value_Type', 'Data_Value', 'Sample_Size']].copy()
bd_df.head()

,Year,LocationAbbr,LocationDesc,Topic,Response,Data_Value_Unit,Data_Value_Type,Data_Value,Sample_Size
0,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,Yes,%,Crude Prevalence,16.9,54.0
1,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,No,%,Crude Prevalence,83.2,54.0
2,2016.0,UW,All States and DC (median) **,Binge Drinking,Yes,%,Crude Prevalence,16.9,51.0
3,2016.0,UW,All States and DC (median) **,Binge Drinking,No,%,Crude Prevalence,83.1,51.0
4,2016.0,AL,Alabama,Binge Drinking,Yes,%,Crude Prevalence,13.0,714.0

In [5]:
bd_df = bd_df.rename(columns = {"Year": "year", "LocationAbbr": "location_abbr", "LocationDesc": "location", "Topic": "topic", "Response": "response", "Data_Value_Unit": "value_unit", "Data_Value_Type": "value_type", "Data_Value": "data_value", "Sample_Size": "sample_size"})
bd_df.head()

,year,location_abbr,location,topic,response,value_unit,value_type,data_value,sample_size
0,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,Yes,%,Crude Prevalence,16.9,54.0
1,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,No,%,Crude Prevalence,83.2,54.0
2,2016.0,UW,All States and DC (median) **,Binge Drinking,Yes,%,Crude Prevalence,16.9,51.0
3,2016.0,UW,All States and DC (median) **,Binge Drinking,No,%,Crude Prevalence,83.1,51.0
4,2016.0,AL,Alabama,Binge Drinking,Yes,%,Crude Prevalence,13.0,714.0

In [8]:
import psycopg2
rds_connection_string = "postgres:postgres@localhost:5432/alcohol_consumption_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [9]:
engine.table_names()

['binge_drinking']

In [10]:
bd_df.to_sql(name='binge_drinking', con=engine, if_exists='append', index=False)

In [11]:
pd.read_sql_query('select * from binge_drinking', con=engine).head()

,year,location_abbr,location,topic,response,value_unit,value_type,data_value,sample_size
0,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,Yes,%,Crude Prevalence,16.9,54.0
1,2016.0,US,"All States, DC and Territories (median) **",Binge Drinking,No,%,Crude Prevalence,83.2,54.0
2,2016.0,UW,All States and DC (median) **,Binge Drinking,Yes,%,Crude Prevalence,16.9,51.0
3,2016.0,UW,All States and DC (median) **,Binge Drinking,No,%,Crude Prevalence,83.1,51.0
4,2016.0,AL,Alabama,Binge Drinking,Yes,%,Crude Prevalence,13.0,714.0